stages:
  - deploy
deploy:
  image: alpine:3
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - apk add --no-cache --update bash openssh rsync sshpass
    - sshpass -V
    - export SSHPASS=$DEV_SSH_PASS
    - sshpass -e ssh -t $DEV_SERVER_USER@$DEV_SERVER "cd $DEV_PATH && git pull && docker compose up -d"
  only:
    - develop
