version: '3'

services:
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - ${SWAGGER_PORT:-8510}:8080
    volumes:
      - ./src:/usr/share/nginx/html/src
    environment:
      - URL=/src/swagger.yaml
